<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="8" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-24T19:05:08 IST" name="Suite" finished-at="2024-08-24T19:05:38 IST" duration-ms="30197">
    <groups>
      <group name="purchasetest">
        <method signature="SubmitOrderTest.orderSubmit(java.util.HashMap)[pri:0, instance:NAutomationTesting.SubmitOrderTest@33bc72d1]" name="orderSubmit" class="NAutomationTesting.SubmitOrderTest"/>
      </group> <!-- purchasetest -->
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.ErrorMsg()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" name="ErrorMsg" class="NAutomationTesting.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2024-08-24T19:05:08 IST" name="SubmitOrderTest" finished-at="2024-08-24T19:05:36 IST" duration-ms="28114">
      <class name="NAutomationTesting.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:NAutomationTesting.SubmitOrderTest@33bc72d1]" started-at="2024-08-24T19:05:09 IST" name="launchApplication" finished-at="2024-08-24T19:05:15 IST" duration-ms="5899" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderSubmit(java.util.HashMap)[pri:0, instance:NAutomationTesting.SubmitOrderTest@33bc72d1]" started-at="2024-08-24T19:05:15 IST" name="orderSubmit" data-provider="getData" finished-at="2024-08-24T19:05:23 IST" duration-ms="8596" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Narasimha@444, product=ADIDAS ORIGINAL, email=narasimhulu3k@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderSubmit -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:NAutomationTesting.SubmitOrderTest@33bc72d1]" started-at="2024-08-24T19:05:23 IST" name="teardown" finished-at="2024-08-24T19:05:23 IST" duration-ms="61" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:NAutomationTesting.SubmitOrderTest@33bc72d1]" started-at="2024-08-24T19:05:23 IST" name="launchApplication" finished-at="2024-08-24T19:05:28 IST" duration-ms="4921" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderSubmit(java.util.HashMap)[pri:0, instance:NAutomationTesting.SubmitOrderTest@33bc72d1]" started-at="2024-08-24T19:05:28 IST" name="orderSubmit" data-provider="getData" finished-at="2024-08-24T19:05:36 IST" duration-ms="7900" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Nani@444, product=ZARA COAT 3, email=narasimhulu2k@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderSubmit -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:NAutomationTesting.SubmitOrderTest@33bc72d1]" started-at="2024-08-24T19:05:36 IST" name="teardown" finished-at="2024-08-24T19:05:36 IST" duration-ms="43" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- NAutomationTesting.SubmitOrderTest -->
    </test> <!-- SubmitOrderTest -->
    <test started-at="2024-08-24T19:05:08 IST" name="ErrorValidationTest" finished-at="2024-08-24T19:05:38 IST" duration-ms="30197">
      <class name="NAutomationTesting.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" started-at="2024-08-24T19:05:08 IST" name="launchApplication" finished-at="2024-08-24T19:05:15 IST" duration-ms="6390" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="ErrorMsg()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" started-at="2024-08-24T19:05:15 IST" name="ErrorMsg" finished-at="2024-08-24T19:05:15 IST" duration-ms="695" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at NAutomationTesting.ErrorValidationTest.ErrorMsg(ErrorValidationTest.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorMsg -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" started-at="2024-08-24T19:05:15 IST" name="teardown" finished-at="2024-08-24T19:05:15 IST" duration-ms="117" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" started-at="2024-08-24T19:05:15 IST" name="launchApplication" finished-at="2024-08-24T19:05:21 IST" duration-ms="5210" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ErrorMsg()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" started-at="2024-08-24T19:05:21 IST" name="ErrorMsg" finished-at="2024-08-24T19:05:21 IST" duration-ms="537" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at NAutomationTesting.ErrorValidationTest.ErrorMsg(ErrorValidationTest.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorMsg -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" started-at="2024-08-24T19:05:22 IST" name="teardown" finished-at="2024-08-24T19:05:22 IST" duration-ms="62" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" started-at="2024-08-24T19:05:22 IST" name="launchApplication" finished-at="2024-08-24T19:05:27 IST" duration-ms="4705" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="getTexterror()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" started-at="2024-08-24T19:05:27 IST" name="getTexterror" finished-at="2024-08-24T19:05:27 IST" duration-ms="467" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTexterror -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" started-at="2024-08-24T19:05:27 IST" name="teardown" finished-at="2024-08-24T19:05:27 IST" duration-ms="48" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" started-at="2024-08-24T19:05:27 IST" name="launchApplication" finished-at="2024-08-24T19:05:32 IST" duration-ms="4909" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="getTexterror2()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" started-at="2024-08-24T19:05:32 IST" name="getTexterror2" finished-at="2024-08-24T19:05:32 IST" duration-ms="413" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTexterror2 -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" started-at="2024-08-24T19:05:32 IST" name="teardown" finished-at="2024-08-24T19:05:32 IST" duration-ms="43" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" started-at="2024-08-24T19:05:32 IST" name="launchApplication" finished-at="2024-08-24T19:05:37 IST" duration-ms="4703" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="getTexterror3()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" started-at="2024-08-24T19:05:37 IST" name="getTexterror3" finished-at="2024-08-24T19:05:38 IST" duration-ms="486" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at NAutomationTesting.ErrorValidationTest.getTexterror3(ErrorValidationTest.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTexterror3 -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:NAutomationTesting.ErrorValidationTest@3ad83a66]" started-at="2024-08-24T19:05:38 IST" name="teardown" finished-at="2024-08-24T19:05:38 IST" duration-ms="42" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- NAutomationTesting.ErrorValidationTest -->
    </test> <!-- ErrorValidationTest -->
  </suite> <!-- Suite -->
</testng-results>
